ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
#  SCENE_DATASET: "replica"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE: 16000
#    RIR_SAMPLING_RATE: 44100
  AGENT_0:
    SENSORS: ['DEPTH_SENSOR']

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['SPECTROGRAM_SENSOR']
  GOAL_SENSOR_UUID: spectrogram

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION', 'SUCCESS', 'SPL', 'SOFT_SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: "AudioNav"
  SPLIT: "val_telephone"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
#  SCENES_DIR: "data/scene_datasets/replica"
#  DATA_PATH: "data/datasets/audionav/replica/{version}/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/audionav/mp3d/{version}/{split}/{split}.json.gz"
